fixtures:

  forge_modules:

    puppi: "example42/puppi"
    stdlib: 'puppetlabs/stdlib'

    epel: 'stahnma/epel'

    concat: 'puppetlabs/concat' # Dependency for PostgreSQL
    postgresql: 'puppetlabs/postgresql'

    firewall: 'puppetlabs/firewall'
    apache: 'puppetlabs/apache'
    php: 'example42/php'

    pear: 'rafaelfc/pear' # Dependency for drush
    drush: 'erikwebb/drush'

  repositories:

    fedora_commons:

      repo: 'git@github.com:LafayetteCollegeLibraries/puppet-fedora_commons.git'
      ref: '33ed9e205e045d8cc030aeea2b118beb91180179'

  symlinks:
    islandora: "#{source_dir}"
